import Head from 'next/head';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import DashboardLayout from '../components/DashboardLayout';

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const path = router.pathname;
  const Page = (
    <>
      <Head>
        <title>CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );

  {
    return /dashboard/.test(path) ? <DashboardLayout>{Page}</DashboardLayout> : Page;
  }
}

export default MyApp;
