import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NormalLoginForm from '../components/NormalLoginForm';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Course Management Assistant</h1>
        <div className={styles.login}>
          <NormalLoginForm />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
